In [38]:
import pandas as pd
import numpy as np

In [39]:
df = pd.read_csv('portugal_listinigs.csv', low_memory=False)
df

,Price,District,City,Town,Type,EnergyCertificate,Floor,NumberOfBathrooms,Parking,TotalArea,...,Garage,Elevator,ElectricCarsCharging,TotalRooms,NumberOfBedrooms,NumberOfWC,ConservationStatus,LivingArea,LotSize,BuiltArea
0,250000.0,Faro,São Brás de Alportel,São Brás de Alportel,Apartment,A+,1st Floor,0.0,1.0,114.0,...,NaN,True,NaN,2.0,NaN,NaN,NaN,114.0,NaN,NaN
1,158000.0,Faro,Portimão,Portimão,Apartment,D,2nd Floor,2.0,1.0,21953.0,...,NaN,True,NaN,1.0,NaN,NaN,NaN,42.0,NaN,48.00
2,19000.0,Faro,Lagoa (Algarve),Estômbar e Parchal,Land,NC,NaN,0.0,0.0,3710.0,...,NaN,False,NaN,NaN,NaN,NaN,NaN,3710.0,NaN,3710.00
3,250000.0,Faro,São Brás de Alportel,São Brás de Alportel,Apartment,A+,1st Floor,2.0,1.0,115.0,...,NaN,True,NaN,2.0,NaN,NaN,NaN,115.0,NaN,NaN
4,2950000.0,Faro,Albufeira,Albufeira e Olhos de Água,Building,NC,NaN,0.0,0.0,265.0,...,NaN,False,NaN,NaN,NaN,NaN,NaN,406.0,NaN,465.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168543,499000.0,Lisboa,Lisboa,Campo de Ourique,Apartment,D,NaN,1.0,0.0,75.0,...,False,True,False,3.0,2.0,NaN,Good condition,65.0,NaN,NaN
168544,1600000.0,Lisboa,Oeiras,"Oeiras e São Julião da Barra, Paço de Arcos e ...",House,C,NaN,4.0,0.0,392.0,...,False,False,False,NaN,7.0,NaN,NaN,352.0,1000.0,NaN
168545,495000.0,Lisboa,Cascais,Carcavelos e Parede,Apartment,E,NaN,1.0,1.0,70.0,...,False,False,True,NaN,2.0,NaN,NaN,85.0,NaN,NaN
168546,319000.0,Setúbal,Barreiro,"Alto do Seixalinho, Santo André e Verderena",Apartment,C,NaN,2.0,1.0,117.0,...,False,True,False,NaN,3.0,NaN,NaN,106.0,NaN,138.13
168547,426000.0,Setúbal,Almada,Costa de Caparica,Apartment,D,NaN,1.0,0.0,52.0,...,False,True,False,NaN,1.0,NaN,NaN,52.0,NaN,52.40

#### Memuat Informasi Data Mentah Sebelum di Cleaning

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 168548 entries, 0 to 168547
Data columns (total 23 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Price                  168147 non-null  float64
 1   District               168548 non-null  object
 2   City                   168548 non-null  object
 3   Town                   168546 non-null  object
 4   Type                   168532 non-null  object
 5   EnergyCertificate      168534 non-null  object
 6   Floor                  27929 non-null   object
 7   NumberOfBathrooms      153833 non-null  float64
 8   Parking                168516 non-null  float64
 9   TotalArea              154760 non-null  float64
 10  ConstructionYear       109836 non-null  float64
 11  EnergyEfficiencyLevel  100301 non-null  object
 12  PublishDate            61024 non-null   object
 13  Garage                 100301 non-null  object
 14  Elevator               168516 non-null  object
 15  ElectricCarsCharging   100301 non-null  object
 16  TotalRooms             84247 non-null   float64
 17  NumberOfBedrooms       69951 non-null   float64
 18  NumberOfWC             69974 non-null   float64
 19  ConservationStatus     27287 non-null   object
 20  LivingArea             130107 non-null  float64
 21  LotSize                56697 non-null   float64
 22  BuiltArea              67466 non-null   float64
dtypes: float64(11), object(12)
memory usage: 29.6+ MB

In [42]:
print(len(df))

168548

#### Membersihkan Data yang Duplikat

In [43]:
df = df.drop_duplicates()

#### Mengkerucutkan Fokus Hanya Kepada Perumahan Saja

In [44]:
df = df[df['Type'].isin(['Apartment', 'House'])]

#### Membersikah Outliers

membuang semua properti yang berada di area yang tidak masuk akal dan juga jenis properti yang memiliki ukuran yang tidak masuk akal untuk di perjual belikan.

In [45]:
df = df[(df['TotalArea'] >= 5) & (df['TotalArea'] <= 1500)]

#### Membersihkan Harga yang Tidak Realistis

membuang semua properti dengan harga di bawah 5000 Euro karena tidak masuk akal.

In [46]:
df = df[df['Price'] > 5000]

#### Mengisi Missing Value Dengan Bool

pada kolom kolom tersebut di pilih menggunakan boolean karena hanya memerlukan keteranyan apakah tersedia atau tidak deimana jika tersedia fasilitas tersebut maka keterangkan yang muncul adalah "True"

In [47]:
df['Garage'] = df['Garage'].fillna(False)
df['Elevator'] = df['Elevator'].fillna(False)
df['ElectricCarsCharging'] = df['ElectricCarsCharging'].fillna(False)

C:\Users\E480\AppData\Local\Temp\ipykernel_18364\2149737296.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Garage'] = df['Garage'].fillna(False)
C:\Users\E480\AppData\Local\Temp\ipykernel_18364\2149737296.py:2: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Elevator'] = df['Elevator'].fillna(False)
C:\Users\E480\AppData\Local\Temp\ipykernel_18364\2149737296.py:3: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['ElectricCarsCharging'] = df['ElectricCarsCharging'].fillna(False)

#### Mengisi Missing Value Dengan Keterangan Lain

pada kolom kolom tersebut di di isi keterangan pada missing value dengan keterangan "Unkown" atau "NC" untuk menjelaskan bahwa membah kotak data tersebut tidak diisi karna kosong atau tidak tersedia

In [48]:
df['ConservationStatus'] = df['ConservationStatus'].fillna('Unknown')
df['EnergyCertificate'] = df['EnergyCertificate'].fillna('NC')

#### Menghapus Semua Baris Kolom Yang Kosong

fungsi ini dilakukan pada kolom berguna untuk bisa membuang semua baris yang tidak memiliki keterangan price dan total area karna hal ini di rasa penting untuk bisa tersedia dan di analisis, selain ini kolom ini penting untuk para calon penbeli sehingga di butuhkan angka yang pasti.

In [49]:
df = df.dropna(subset=['Price', 'TotalArea'])

#### Menghapus Barisan yang tidak Memiliki Kamar mandi

di dalam data terdapat beberapa rumah dan apartemen yang tidak memiliki kamar mandi sehingga dirasa hal ini tidak masuk akal dan perlu di hapus saja

In [50]:
df = df[df['NumberOfBathrooms'] > 0]

#### Mengisi Missing Value Dengan Median

Jumlah kamar yang datanya hilang di isi dengan median untuk sebagai nilai tengah

In [51]:
df['NumberOfBedrooms'] = df['NumberOfBedrooms'].fillna(df['NumberOfBedrooms'].median())

#### Menghapus Row yang Tidak Memiliki Publish Date

dilakukan untuk bisa menganalisis trend pasar yang ada, walaupun datanya berkurang jauh tetapi penting untuk bisa menyajikan data dengan quality yang baik di banding quantity

In [52]:
df = df.dropna(subset=['PublishDate'])

#### Membuat Tabel Final yang Berisikian Kolom Kolom yang Hanya Digunakan Untuk di Analisis

In [53]:
kolom_diikuti = ['Price', 'District', 'City', 'Town', 'Type', 'EnergyCertificate', 
                 'NumberOfBathrooms', 'TotalArea', 'PublishDate', 'Garage', 
                 'Elevator', 'NumberOfBedrooms', 'ConservationStatus']
df_final = df[kolom_diikuti]

In [54]:
print(len(df_final))

38758

#### Hasil Data Final

In [55]:
df_final

,Price,District,City,Town,Type,EnergyCertificate,NumberOfBathrooms,TotalArea,PublishDate,Garage,Elevator,NumberOfBedrooms,ConservationStatus
68195,62000.0,Aveiro,Ovar,Válega,House,F,1.0,336.0,2024-10-21 15:56:26.597,False,False,2.0,Unknown
68196,236000.0,Aveiro,Oliveira do Bairro,Oiã,Apartment,E,2.0,183.0,2024-10-11 16:14:39.720,True,True,4.0,Reasonable
68197,220000.0,Aveiro,Oliveira do Bairro,Palhaça,House,F,1.0,154.0,2024-10-18 14:27:49.537,True,False,4.0,Unknown
68230,182000.0,Aveiro,Espinho,Espinho,Apartment,D,2.0,61.0,2024-10-17 13:40:14.797,False,False,2.0,Unknown
68231,37000.0,Aveiro,Ílhavo,São Salvador,House,NC,2.0,140.0,2024-10-18 16:15:40.007,False,False,3.0,Unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...
168543,499000.0,Lisboa,Lisboa,Campo de Ourique,Apartment,D,1.0,75.0,2026-07-11 09:23:21.600,False,True,2.0,Good condition
168544,1600000.0,Lisboa,Oeiras,"Oeiras e São Julião da Barra, Paço de Arcos e ...",House,C,4.0,392.0,2026-07-11 17:45:02.697,False,False,7.0,Unknown
168545,495000.0,Lisboa,Cascais,Carcavelos e Parede,Apartment,E,1.0,70.0,2026-07-11 12:57:46.217,False,False,2.0,Unknown
168546,319000.0,Setúbal,Barreiro,"Alto do Seixalinho, Santo André e Verderena",Apartment,C,2.0,117.0,2026-07-11 15:14:53.197,False,True,3.0,Unknown
168547,426000.0,Setúbal,Almada,Costa de Caparica,Apartment,D,1.0,52.0,2026-07-11 11:32:40.940,False,True,1.0,Unknown

#### Informasi Mengenai Data Final

In [56]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
Index: 38758 entries, 68195 to 168547
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Price               38758 non-null  float64
 1   District            38758 non-null  object
 2   City                38758 non-null  object
 3   Town                38758 non-null  object
 4   Type                38758 non-null  object
 5   EnergyCertificate   38758 non-null  object
 6   NumberOfBathrooms   38758 non-null  float64
 7   TotalArea           38758 non-null  float64
 8   PublishDate         38758 non-null  object
 9   Garage              38758 non-null  bool
 10  Elevator            38758 non-null  bool
 11  NumberOfBedrooms    38758 non-null  float64
 12  ConservationStatus  38758 non-null  object
dtypes: bool(2), float64(4), object(7)
memory usage: 3.6+ MB

In [57]:
df_final.to_csv('portugal_listings_clean_fix1.csv', index=False)